services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=segundas-huellas'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/segundas-huellas
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - CLOUDINARY_URL=cloudinary://367656173992544:ErIitGo4UksnWrB3K2W9LcSBoFA@dffbmjmgj
        - DEFAULT_PET_PHOTO=https://res.cloudinary.com/dgdxraapm/image/upload/v1732583288/pet-photos/default.jpg