spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

## Application Configuration
app:
  seeding:
    enabled: true
    batch-size: 50
    pets:
      count: 1000
  error:
    base-uri: https://api.domainplaceholder.com/errors/
  default:
    pet-photo: ${DEFAULT_PET_PHOTO:}
  cloudinary:
    url: ${CLOUDINARY_URL:}

## Dev only configuration
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/segundas-huellas  # Conexión a la base de datos en Docker (localhost)
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true

logging:
  level:
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.SegundasHuellas.backend: DEBUG

## Docker configuration
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/segundas-huellas
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  seeding:
    enabled: true
    batch-size: 50
    pets:
      count: 1000
  error:
    base-uri: https://api.domainplaceholder.com/errors/
  cloudinary:
    url: ${CLOUDINARY_URL}
  default:
    pet-photo: ${DEFAULT_PET_PHOTO}


## Docker Compose Configuration (aplica a todos los perfiles)
---
spring:
  docker:
    compose:
      lifecycle-management: start_only
      file: ./backend/compose.yaml