spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  docker:
    compose:
      lifecycle-management: start_only
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


## Application Configuration
app:
  error:
    base-uri: https://api.domainplaceholder.com/errors/
  cloudinary:
    url: ${CLOUDINARY_URL:}

## Dev only configuration
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.SegundasHuellas.backend: DEBUG