spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
      file: classpath:compose.yaml
## Application Configuration
app:
  seeding:
    enabled: true
    batch-size: 50
    pets:
      count: 1000
  error:
    base-uri: https://api.segundas-huellas.com/errors/
  default:
    pet-photo: ${DEFAULT_PET_PHOTO:}
    user-profile-photo: ${DEFAULT_USER_PROFILE_PHOTO:}
  cloudinary:
    url: ${CLOUDINARY_URL:}
  security:
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGINS}
    token:
      cleanup-cron: "0 0 2 * * *"
      retention-days: 7
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger
    operations-sorter: method
    tags-sorter: alpha

## Dev only configuration
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/segundas-huellas  # Conexión a la base de datos en Docker (localhost)
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true

logging:
  pattern:
    console: "%d{HH:mm:ss} %clr(%-5level) [%-30.30logger{0}] %msg%n"
  level:
      org.springframework.security: DEBUG
      org.springframework.security.web: DEBUG
      org.springframework.security.authentication: DEBUG
      org.springframework.security.access: DEBUG
      org.springframework.security.core: DEBUG
#    org.hibernate.stat: ERROR
#    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    com.SegundasHuellas.backend: DEBUG
